title: 春秋亭
description: "Shuoxue Li, Department of Chemistry and Chemical Engineering, Caltech"
remote_theme: pages-themes/dinky@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
