- menu_name: "Links"

- name: "Chan Group"
  url: "https://www.chan-lab.caltech.edu/"

- name: "Caltech"
  url: "https://www.caltech.edu/"

- name: "TMC Group"
  url: "https://www.chem.pku.edu.cn/jianghgroup/"

- name: "PySCF"
  url: "https://pyscf.org/"
