- menu_name: "Institute Links"

- name: "Caltech"
  url: "https://www.caltech.edu/"

- name: "Peking University"
  url: "https://english.pku.edu.cn/"

- name: "Chan Group"
  url: "https://www.chan-lab.caltech.edu/"

- name: "TMC Group"
  url: "https://www.chem.pku.edu.cn/jianghgroup/"
